### PR TITLE
New readme.md with formatted text and images

### PR DESCRIPTION
**Pull request by MakeItBack**
Shabaz - I've replaced the text-only readme file for this project with one written in markdown (README.md) which allowed me to add text formatting/images/links. Hope you're happy with it - I've used your blog post to provide the content. Hopefully I've completed the git process properly to fork-clone-branch etc. - let me know if anything looks amiss. Would be really great if you provide a feedback message back to asking me for  changes first i.e. don't merge it yet. Would be good to see how that looks when the repo owner replies, requesting changes before they will be happy with it.

The other thing I was going to do was add a license file to the repo. I can still do this (would be better as a separate PR anyway) but the thing I ran into was that the creative commons license you were quoting doesn't sound like it is appropriate for software. See: [here](https://softwareengineering.stackexchange.com/questions/110583/software-license-restricting-commercial-usage-like-cc-by-nc-sa?rq=1) and [here](https://www.quora.com/Is-there-a-license-like-the-CC-BY-NC-SA-for-software).  I don't know if it's any good, but a post in Quora suggests the [Non-Profit Open Software License 3.0 (NPOSL-3.0)](https://tldrlegal.com/license/non-profit-open-software-license-3.0-(nposl-3.0)) is an option.

Thanks again for letting me play around with your stuff, you are a champion sir. I'm learning a lot!

### CODE REVIEW

**Comment by MakeItBack** [comment]
**Just read this on the Hacktoberfest site:**<br>
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. **Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.**

Info here: **[Link to Hacktoberfest site about adding the label](https://hacktoberfest.digitalocean.com/hacktoberfest-update)**

**Review by shabaz123 — COMMENTED** [review]
Hi Mike,

This is a comment that is looks good! I'm happy to click Approve, or click Request changes, these are the two options available to me apart from Comment (which I'm doing now). Here is what I saw when I clicked in my e-mail to see your pull request, and when I clicked on one of the files to see the changes you made.  See the two attached .png files.
received-pull-request
viewing-your-draft

**Comment by MakeItBack** [comment]
Great! So far so good! So can I ask for two things - 1) label the PR with "hacktoberfest-accepted" (link on how to do this is in comment above) and 2) click Request changes so I can see how this looks when I get a PR returned with comments. I will change something small, then I will re-submit the PR to you after that and you can accept it then.

**Review by shabaz123 — CHANGES_REQUESTED** [review]
Yeess requesting a change : )
On the pull request page, I added a label. Then I clicked on the change, and then clicked on Review changes as before, and this time selected Request changes instead of Comment.
Once you're ready with a change, I'll approve.

**Review by shabaz123 — APPROVED** [review]
Approving the "This license type is under review and will be updated shortly" update!

**Pull request merged**
